name: release-tflint

on:
  push:
    tags:
    - tflint-ruleset-blueprint/v*.*.*

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tflint-ruleset-blueprint'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'tflint-ruleset-blueprint/go.mod'
    - run: echo "GORELEASER_CURRENT_TAG=${GITHUB_REF#refs/tags/tflint-ruleset-blueprint/}" >> $GITHUB_ENV
    - run: echo "${{env.GORELEASER_CURRENT_TAG}}"
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --clean --skip=validate,publish
        workdir: tflint-ruleset-blueprint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
